#mybatis配置
mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
    mapper-locations: classpath:maping/*.xml
#分页插件配置
pagehelper:
    helperDialect: mysql
    params: count=countSql
    reasonable: false
    supportMethodsArguments: false
spring:
    profiles:
        active: dev
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
      timeout: 5000